info: ""
rng_seed: 0
model_name: "paper"
loss: "hinge"
alpha: 1e-3
data:
  num_train: 250
  num_test: 500
  dim: 5
batch_size: -1
epochs: 500

hydra:
  job:
    chdir: True
  run:
    dir: outputs/train_stripe/${now:%Y-%m-%d}/${now:%H-%M-%S}


defaults:
  - _self_
  - model/config
  - metrics/config
    