info: ""
model_name: "paper"
loss: "hinge"
alpha: 1e-3
data:
  num_train: 250
  num_test: 100
  dim: 5
batch_size: -1
epochs: 500

hydra:
  job:
    chdir: True


defaults:
  - _self_
  - model/config
  - metrics/config
    