info: ""
seed: 0
architecture: [64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M']
data:
  batch_size: 128
optimizer:
  type: adam
  spec:
    learning_rate: 1e-3
epochs: 1000









hydra:
  job:
    chdir: True
  run:
    dir: outputs/train_cnn/${now:%Y-%m-%d}/${now:%H-%M-%S}
